name: py36mayavi
channels:
  - conda-forge
  - defaults
dependencies:
  - apptools=4.4.0=py36_0
  - bottleneck=1.2.1=py36_1
  - click=6.7=py_1
  - cloudpickle=0.5.2=py_0
  - curl=7.55.1=vc14_0
  - dask=0.17.0=py_0
  - dask-core=0.17.0=py_0
  - distributed=1.21.0=py36_0
  - envisage=4.5.1=py36_0
  - expat=2.2.5=vc14_0
  - freetype=2.7=vc14_1
  - future=0.16.0=py36_0
  - h5netcdf=0.5.0=py_0
  - hdf4=4.2.13=vc14_0
  - heapdict=1.0.0=py36_0
  - icu=58.2=vc14_0
  - jinja2=2.10=py36_0
  - jpeg=9b=vc14_2
  - krb5=1.14.2=vc14_0
  - libiconv=1.14=vc14_4
  - libpng=1.6.34=vc14_0
  - libssh2=1.8.0=vc14_2
  - libtiff=4.0.9=vc14_0
  - libxml2=2.9.5=vc14_1
  - locket=0.2.0=py36_1
  - markupsafe=1.0=py36_0
  - mayavi=4.5.0=py36_vc14_3
  - msgpack-python=0.5.1=py36_0
  - pandas=0.22.0=py36_0
  - partd=0.3.8=py36_0
  - pip=9.0.1=py36_1
  - psutil=5.4.0=py36_0
  - pyface=5.1.0=py36_1
  - pygments=2.2.0=py36_0
  - pyqt=4.11.4=py36_2
  - python=3.6.4=0
  - python-dateutil=2.6.1=py36_0
  - pytz=2017.3=py_2
  - pyyaml=3.12=py36_1
  - qt=4.8.7=vc14_7
  - qtpy=1.3.1=py36_0
  - setuptools=38.4.0=py36_0
  - sip=4.18=py36_1
  - six=1.11.0=py36_1
  - sortedcontainers=1.5.7=py36_0
  - tbb=2018_20171205=vc14_0
  - tblib=1.3.2=py36_0
  - toolz=0.8.2=py_2
  - tornado=4.5.3=py36_0
  - traits=4.6.0=py36_1
  - traitsui=5.1.0=py36_0
  - vc=14=0
  - vs2015_runtime=14.0.25420=0
  - vtk=7.1.1=py36_202
  - wheel=0.30.0=py36_2
  - wincertstore=0.2=py36_0
  - winpty=0.4.3=vc14_2
  - xarray=0.10.0=py36_0
  - yaml=0.1.7=vc14_0
  - zict=0.1.3=py_0
  - zlib=1.2.11=vc14_0
  - astroid=1.6.4=py36_0
  - backcall=0.1.0=py36_0
  - bleach=2.1.3=py36_0
  - bokeh=0.12.16=py36_0
  - bzip2=1.0.6=hfa6e2cd_5
  - ca-certificates=2018.03.07=0
  - certifi=2018.4.16=py36_0
  - cftime=1.0.0b1=py36h452e1ab_0
  - colorama=0.3.9=py36h029ae33_0
  - configobj=5.0.6=py36_0
  - decorator=4.3.0=py36_0
  - entrypoints=0.2.3=py36hfd66bb0_2
  - h5py=2.8.0=py36h3bdd7fb_0
  - hdf5=1.10.2=hac2f561_1
  - html5lib=1.0.1=py36h047fa9f_0
  - icc_rt=2017.0.4=h97af966_0
  - intel-openmp=2018.0.0=hd92c6cd_8
  - ipykernel=4.8.2=py36_0
  - ipython=6.4.0=py36_0
  - ipython_genutils=0.2.0=py36h3c5d0ee_0
  - ipywidgets=7.2.1=py36_0
  - isort=4.3.4=py36_0
  - jedi=0.12.0=py36_1
  - jsonschema=2.6.0=py36h7636477_0
  - jupyter_client=5.2.3=py36_0
  - jupyter_core=4.4.0=py36h56e9d50_0
  - lazy-object-proxy=1.3.1=py36hd1c21d2_0
  - libcurl=7.60.0=hc4dcbb0_0
  - libnetcdf=4.6.1=h62daf8c_0
  - libsodium=1.0.16=h9d3ae62_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - mccabe=0.6.1=py36hb41005a_1
  - mistune=0.8.3=py36hfa6e2cd_1
  - mkl=2018.0.1=h2108138_4
  - msys2-conda-epoch=20160418=1
  - nbconvert=5.3.1=py36h8dc0fde_0
  - nbformat=4.4.0=py36h3a5bc1b_0
  - netcdf4=1.4.0=py36hbfe741f_1
  - notebook=5.5.0=py36_0
  - numpy=1.14.0=py36h4a99626_1
  - openssl=1.0.2o=h8ea7d77_0
  - packaging=17.1=py36_0
  - pandoc=1.19.2.1=hb2460c7_1
  - pandocfilters=1.4.2=py36h3ef6317_1
  - parso=0.2.1=py36_0
  - pickleshare=0.7.4=py36h9de030f_0
  - prompt_toolkit=1.0.15=py36h60b8f86_0
  - pylint=1.9.1=py36_0
  - pyparsing=2.2.0=py36h785a196_1
  - pywinpty=0.5.3=py36_0
  - pyzmq=17.0.0=py36hfa6e2cd_1
  - scipy=1.0.0=py36h1260518_0
  - send2trash=1.5.0=py36_0
  - simplegeneric=0.8.1=py36_2
  - terminado=0.8.1=py36_1
  - testpath=0.3.1=py36h2698cfe_0
  - traitlets=4.3.2=py36h096827d_0
  - wcwidth=0.1.7=py36h3d5aa90_0
  - webencodings=0.5.1=py36h67c50ae_1
  - widgetsnbextension=3.2.1=py36_0
  - wrapt=1.10.11=py36he5f5981_0
  - zeromq=4.2.5=hc6251cf_0
  - pip:
    - cycler==0.10.0
    - eegvis==0.0.1
    - kiwisolver==1.0.1
    - matplotlib==2.2.2
    - nk-database-proj==0.0.1
    - pyqtgraph==0.10.0
prefix: C:\Users\clee\Anaconda3\envs\py36mayavi
